// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace TodoUiTest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public partial class UIMap
    {
        
        #region Properties
        public UIToDoListWindow UIToDoListWindow
        {
            get
            {
                if ((this.mUIToDoListWindow == null))
                {
                    this.mUIToDoListWindow = new UIToDoListWindow();
                }
                return this.mUIToDoListWindow;
            }
        }
        
        public UIToDoListWindow1 UIToDoListWindow1
        {
            get
            {
                if ((this.mUIToDoListWindow1 == null))
                {
                    this.mUIToDoListWindow1 = new UIToDoListWindow1();
                }
                return this.mUIToDoListWindow1;
            }
        }
        #endregion
        
        #region Fields
        private UIToDoListWindow mUIToDoListWindow;
        
        private UIToDoListWindow1 mUIToDoListWindow1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIToDoListWindow : WpfWindow
    {
        
        public UIToDoListWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "ToDoList";
            this.SearchProperties["FrameworkId"] = "WPF";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("ToDoList");
            #endregion
        }
        
        #region Properties
        public WpfButton ClearCompletedButton
        {
            get
            {
                if ((this.mClearCompletedButton == null))
                {
                    this.mClearCompletedButton = new WpfButton(this);
                    #region Search Criteria
                    this.mClearCompletedButton.SearchProperties["FrameworkId"] = "WPF";
                    this.mClearCompletedButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "ClearCompletedButton";
                    this.mClearCompletedButton.WindowTitles.Add("ToDoList");
                    #endregion
                }
                return this.mClearCompletedButton;
            }
        }
        
        public WpfButton AddTaskBtn
        {
            get
            {
                if ((this.mAddTaskBtn == null))
                {
                    this.mAddTaskBtn = new WpfButton(this);
                    #region Search Criteria
                    this.mAddTaskBtn.SearchProperties["FrameworkId"] = "WPF";
                    this.mAddTaskBtn.SearchProperties[WpfButton.PropertyNames.AutomationId] = "AddTaskBtn";
                    this.mAddTaskBtn.WindowTitles.Add("ToDoList");
                    #endregion
                }
                return this.mAddTaskBtn;
            }
        }
        
        public TaskList TaskList
        {
            get
            {
                if ((this.mTaskList == null))
                {
                    this.mTaskList = new TaskList(this);
                }
                return this.mTaskList;
            }
        }
        
        public WpfEdit NewTaskForm
        {
            get
            {
                if ((this.mNewTaskForm == null))
                {
                    this.mNewTaskForm = new WpfEdit(this);
                    #region Search Criteria
                    this.mNewTaskForm.SearchProperties["FrameworkId"] = "WPF";
                    this.mNewTaskForm.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "NewTaskForm";
                    this.mNewTaskForm.WindowTitles.Add("ToDoList");
                    #endregion
                }
                return this.mNewTaskForm;
            }
        }
        
        public UIItemList UIItemList
        {
            get
            {
                if ((this.mUIItemList == null))
                {
                    this.mUIItemList = new UIItemList(this);
                }
                return this.mUIItemList;
            }
        }
        
        public TaskLeftLabel TaskLeftLabel
        {
            get
            {
                if ((this.mTaskLeftLabel == null))
                {
                    this.mTaskLeftLabel = new TaskLeftLabel(this);
                }
                return this.mTaskLeftLabel;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mClearCompletedButton;
        
        private WpfButton mAddTaskBtn;
        
        private TaskList mTaskList;
        
        private WpfEdit mNewTaskForm;
        
        private UIItemList mUIItemList;
        
        private TaskLeftLabel mTaskLeftLabel;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class TaskList : WpfList
    {
        
        public TaskList(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["FrameworkId"] = "WPF";
            this.SearchProperties[WpfList.PropertyNames.AutomationId] = "TaskList";
            this.WindowTitles.Add("ToDoList");
            #endregion
        }
        
        #region Properties
        public TaskItemListItem TaskItemListItem
        {
            get
            {
                if ((this.mTaskItemListItem == null))
                {
                    this.mTaskItemListItem = new TaskItemListItem(this);
                }
                return this.mTaskItemListItem;
            }
        }
        
        public TaskItemListItem2 TaskItemListItem2
        {
            get
            {
                if ((this.mTaskItemListItem2 == null))
                {
                    this.mTaskItemListItem2 = new TaskItemListItem2(this);
                }
                return this.mTaskItemListItem2;
            }
        }
        #endregion
        
        #region Fields
        private TaskItemListItem mTaskItemListItem;
        
        private TaskItemListItem2 mTaskItemListItem2;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class TaskItemListItem : WpfListItem
    {
        
        public TaskItemListItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["FrameworkId"] = "WPF";
            this.SearchProperties[WpfListItem.PropertyNames.AutomationId] = "Task_1";
            this.WindowTitles.Add("ToDoList");
            #endregion
        }
        
        #region Properties
        public WpfButton UITask_1ToggleButton
        {
            get
            {
                if ((this.mUITask_1ToggleButton == null))
                {
                    this.mUITask_1ToggleButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUITask_1ToggleButton.SearchProperties["FrameworkId"] = "WPF";
                    this.mUITask_1ToggleButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "Task_1-Toggle";
                    this.mUITask_1ToggleButton.WindowTitles.Add("ToDoList");
                    #endregion
                }
                return this.mUITask_1ToggleButton;
            }
        }
        
        public WpfEdit UITask_1DescriptionEdit
        {
            get
            {
                if ((this.mUITask_1DescriptionEdit == null))
                {
                    this.mUITask_1DescriptionEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUITask_1DescriptionEdit.SearchProperties["FrameworkId"] = "WPF";
                    this.mUITask_1DescriptionEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "Task_1-Description";
                    this.mUITask_1DescriptionEdit.WindowTitles.Add("ToDoList");
                    #endregion
                }
                return this.mUITask_1DescriptionEdit;
            }
        }
        
        public WpfButton UITask_1DeleteButton
        {
            get
            {
                if ((this.mUITask_1DeleteButton == null))
                {
                    this.mUITask_1DeleteButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUITask_1DeleteButton.SearchProperties["FrameworkId"] = "WPF";
                    this.mUITask_1DeleteButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "Task_1-Delete";
                    this.mUITask_1DeleteButton.WindowTitles.Add("ToDoList");
                    #endregion
                }
                return this.mUITask_1DeleteButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUITask_1ToggleButton;
        
        private WpfEdit mUITask_1DescriptionEdit;
        
        private WpfButton mUITask_1DeleteButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class TaskItemListItem2 : WpfListItem
    {
        
        public TaskItemListItem2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["FrameworkId"] = "WPF";
            this.SearchProperties[WpfListItem.PropertyNames.AutomationId] = "Task_2";
            this.WindowTitles.Add("ToDoList");
            #endregion
        }
        
        #region Properties
        public WpfEdit UITask_2DescriptionEdit
        {
            get
            {
                if ((this.mUITask_2DescriptionEdit == null))
                {
                    this.mUITask_2DescriptionEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUITask_2DescriptionEdit.SearchProperties["FrameworkId"] = "WPF";
                    this.mUITask_2DescriptionEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "Task_2-Description";
                    this.mUITask_2DescriptionEdit.WindowTitles.Add("ToDoList");
                    #endregion
                }
                return this.mUITask_2DescriptionEdit;
            }
        }
        
        public WpfButton UITask_2ToggleButton
        {
            get
            {
                if ((this.mUITask_2ToggleButton == null))
                {
                    this.mUITask_2ToggleButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUITask_2ToggleButton.SearchProperties["FrameworkId"] = "WPF";
                    this.mUITask_2ToggleButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "Task_2-Toggle";
                    this.mUITask_2ToggleButton.WindowTitles.Add("ToDoList");
                    #endregion
                }
                return this.mUITask_2ToggleButton;
            }
        }
        
        public WpfButton UITask_2DeleteButton
        {
            get
            {
                if ((this.mUITask_2DeleteButton == null))
                {
                    this.mUITask_2DeleteButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUITask_2DeleteButton.SearchProperties["FrameworkId"] = "WPF";
                    this.mUITask_2DeleteButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "Task_2-Delete";
                    this.mUITask_2DeleteButton.WindowTitles.Add("ToDoList");
                    #endregion
                }
                return this.mUITask_2DeleteButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfEdit mUITask_2DescriptionEdit;
        
        private WpfButton mUITask_2ToggleButton;
        
        private WpfButton mUITask_2DeleteButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIItemList : WpfList
    {
        
        public UIItemList(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["FrameworkId"] = "WPF";
            this.WindowTitles.Add("ToDoList");
            #endregion
        }
        
        #region Properties
        public UIAllListItem UIAllListItem
        {
            get
            {
                if ((this.mUIAllListItem == null))
                {
                    this.mUIAllListItem = new UIAllListItem(this);
                }
                return this.mUIAllListItem;
            }
        }
        
        public UIActiveListItem UIActiveListItem
        {
            get
            {
                if ((this.mUIActiveListItem == null))
                {
                    this.mUIActiveListItem = new UIActiveListItem(this);
                }
                return this.mUIActiveListItem;
            }
        }
        
        public UICompletedListItem UICompletedListItem
        {
            get
            {
                if ((this.mUICompletedListItem == null))
                {
                    this.mUICompletedListItem = new UICompletedListItem(this);
                }
                return this.mUICompletedListItem;
            }
        }
        #endregion
        
        #region Fields
        private UIAllListItem mUIAllListItem;
        
        private UIActiveListItem mUIActiveListItem;
        
        private UICompletedListItem mUICompletedListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIAllListItem : WpfListItem
    {
        
        public UIAllListItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["FrameworkId"] = "WPF";
            this.SearchProperties[WpfListItem.PropertyNames.Name] = "All";
            this.WindowTitles.Add("ToDoList");
            #endregion
        }
        
        #region Properties
        public WpfText AllPane
        {
            get
            {
                if ((this.mAllPane == null))
                {
                    this.mAllPane = new WpfText(this);
                    #region Search Criteria
                    this.mAllPane.SearchProperties["FrameworkId"] = "WPF";
                    this.mAllPane.SearchProperties[WpfText.PropertyNames.AutomationId] = "AllPane";
                    this.mAllPane.WindowTitles.Add("ToDoList");
                    #endregion
                }
                return this.mAllPane;
            }
        }
        #endregion
        
        #region Fields
        private WpfText mAllPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIActiveListItem : WpfListItem
    {
        
        public UIActiveListItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["FrameworkId"] = "WPF";
            this.SearchProperties[WpfListItem.PropertyNames.Name] = "Active";
            this.WindowTitles.Add("ToDoList");
            #endregion
        }
        
        #region Properties
        public WpfText ActivePane
        {
            get
            {
                if ((this.mActivePane == null))
                {
                    this.mActivePane = new WpfText(this);
                    #region Search Criteria
                    this.mActivePane.SearchProperties["FrameworkId"] = "WPF";
                    this.mActivePane.SearchProperties[WpfText.PropertyNames.AutomationId] = "ActivePane";
                    this.mActivePane.WindowTitles.Add("ToDoList");
                    #endregion
                }
                return this.mActivePane;
            }
        }
        #endregion
        
        #region Fields
        private WpfText mActivePane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UICompletedListItem : WpfListItem
    {
        
        public UICompletedListItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["FrameworkId"] = "WPF";
            this.SearchProperties[WpfListItem.PropertyNames.Name] = "Completed";
            this.WindowTitles.Add("ToDoList");
            #endregion
        }
        
        #region Properties
        public WpfText CompletedPane
        {
            get
            {
                if ((this.mCompletedPane == null))
                {
                    this.mCompletedPane = new WpfText(this);
                    #region Search Criteria
                    this.mCompletedPane.SearchProperties["FrameworkId"] = "WPF";
                    this.mCompletedPane.SearchProperties[WpfText.PropertyNames.AutomationId] = "CompletedPane";
                    this.mCompletedPane.WindowTitles.Add("ToDoList");
                    #endregion
                }
                return this.mCompletedPane;
            }
        }
        #endregion
        
        #region Fields
        private WpfText mCompletedPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class TaskLeftLabel : WpfText
    {
        
        public TaskLeftLabel(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["FrameworkId"] = "WPF";
            this.SearchProperties[WpfText.PropertyNames.AutomationId] = "TasksLeftMessage";
            this.WindowTitles.Add("ToDoList");
            #endregion
        }
        
        #region Properties
        public WpfText UIItem1taskleftText1
        {
            get
            {
                if ((this.mUIItem1taskleftText1 == null))
                {
                    this.mUIItem1taskleftText1 = new WpfText(this);
                    #region Search Criteria
                    this.mUIItem1taskleftText1.SearchProperties["FrameworkId"] = "WPF";
                    this.mUIItem1taskleftText1.SearchProperties[WpfText.PropertyNames.Name] = "1 task left";
                    this.mUIItem1taskleftText1.SearchConfigurations.Add(SearchConfiguration.DisambiguateChild);
                    this.mUIItem1taskleftText1.WindowTitles.Add("ToDoList");
                    #endregion
                }
                return this.mUIItem1taskleftText1;
            }
        }
        
        public WpfText UIItem3taskleftText1
        {
            get
            {
                if ((this.mUIItem3taskleftText1 == null))
                {
                    this.mUIItem3taskleftText1 = new WpfText(this);
                    #region Search Criteria
                    this.mUIItem3taskleftText1.SearchProperties["FrameworkId"] = "WPF";
                    this.mUIItem3taskleftText1.SearchProperties[WpfText.PropertyNames.Name] = "3 task left";
                    this.mUIItem3taskleftText1.SearchConfigurations.Add(SearchConfiguration.DisambiguateChild);
                    this.mUIItem3taskleftText1.WindowTitles.Add("ToDoList");
                    #endregion
                }
                return this.mUIItem3taskleftText1;
            }
        }
        #endregion
        
        #region Fields
        private WpfText mUIItem1taskleftText1;
        
        private WpfText mUIItem3taskleftText1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIToDoListWindow1 : WpfWindow
    {
        
        public UIToDoListWindow1()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "ToDoList";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("ToDoList");
            #endregion
        }
        
        #region Properties
        public UITaskListList UITaskListList
        {
            get
            {
                if ((this.mUITaskListList == null))
                {
                    this.mUITaskListList = new UITaskListList(this);
                }
                return this.mUITaskListList;
            }
        }
        #endregion
        
        #region Fields
        private UITaskListList mUITaskListList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UITaskListList : WpfList
    {
        
        public UITaskListList(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfList.PropertyNames.AutomationId] = "TaskList";
            this.WindowTitles.Add("ToDoList");
            #endregion
        }
        
        #region Properties
        public UIToDoMvvmTaskItemListItem UIToDoMvvmTaskItemListItem
        {
            get
            {
                if ((this.mUIToDoMvvmTaskItemListItem == null))
                {
                    this.mUIToDoMvvmTaskItemListItem = new UIToDoMvvmTaskItemListItem(this);
                }
                return this.mUIToDoMvvmTaskItemListItem;
            }
        }
        #endregion
        
        #region Fields
        private UIToDoMvvmTaskItemListItem mUIToDoMvvmTaskItemListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIToDoMvvmTaskItemListItem : WpfListItem
    {
        
        public UIToDoMvvmTaskItemListItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfListItem.PropertyNames.AutomationId] = "Task_1";
            this.WindowTitles.Add("ToDoList");
            #endregion
        }
        
        #region Properties
        public WpfCheckBox UITask_1ToggleCheckBox
        {
            get
            {
                if ((this.mUITask_1ToggleCheckBox == null))
                {
                    this.mUITask_1ToggleCheckBox = new WpfCheckBox(this);
                    #region Search Criteria
                    this.mUITask_1ToggleCheckBox.SearchProperties[WpfCheckBox.PropertyNames.AutomationId] = "Task_1-Toggle";
                    this.mUITask_1ToggleCheckBox.WindowTitles.Add("ToDoList");
                    #endregion
                }
                return this.mUITask_1ToggleCheckBox;
            }
        }
        #endregion
        
        #region Fields
        private WpfCheckBox mUITask_1ToggleCheckBox;
        #endregion
    }
}
